package com.ymatou.liveinfo.infrastructure.db.model;

import java.util.ArrayList;
import java.util.List;

public class CountryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public CountryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCountryIdIsNull() {
            addCriterion("iCountryId is null");
            return (Criteria) this;
        }

        public Criteria andCountryIdIsNotNull() {
            addCriterion("iCountryId is not null");
            return (Criteria) this;
        }

        public Criteria andCountryIdEqualTo(Integer value) {
            addCriterion("iCountryId =", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotEqualTo(Integer value) {
            addCriterion("iCountryId <>", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdGreaterThan(Integer value) {
            addCriterion("iCountryId >", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("iCountryId >=", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdLessThan(Integer value) {
            addCriterion("iCountryId <", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdLessThanOrEqualTo(Integer value) {
            addCriterion("iCountryId <=", value, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdIn(List<Integer> values) {
            addCriterion("iCountryId in", values, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotIn(List<Integer> values) {
            addCriterion("iCountryId not in", values, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdBetween(Integer value1, Integer value2) {
            addCriterion("iCountryId between", value1, value2, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("iCountryId not between", value1, value2, "countryId");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNull() {
            addCriterion("sCountryName is null");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNotNull() {
            addCriterion("sCountryName is not null");
            return (Criteria) this;
        }

        public Criteria andCountryNameEqualTo(String value) {
            addCriterion("sCountryName =", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotEqualTo(String value) {
            addCriterion("sCountryName <>", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThan(String value) {
            addCriterion("sCountryName >", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThanOrEqualTo(String value) {
            addCriterion("sCountryName >=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThan(String value) {
            addCriterion("sCountryName <", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThanOrEqualTo(String value) {
            addCriterion("sCountryName <=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLike(String value) {
            addCriterion("sCountryName like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotLike(String value) {
            addCriterion("sCountryName not like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameIn(List<String> values) {
            addCriterion("sCountryName in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotIn(List<String> values) {
            addCriterion("sCountryName not in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameBetween(String value1, String value2) {
            addCriterion("sCountryName between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotBetween(String value1, String value2) {
            addCriterion("sCountryName not between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhIsNull() {
            addCriterion("sCountryNameZh is null");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhIsNotNull() {
            addCriterion("sCountryNameZh is not null");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhEqualTo(String value) {
            addCriterion("sCountryNameZh =", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhNotEqualTo(String value) {
            addCriterion("sCountryNameZh <>", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhGreaterThan(String value) {
            addCriterion("sCountryNameZh >", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhGreaterThanOrEqualTo(String value) {
            addCriterion("sCountryNameZh >=", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhLessThan(String value) {
            addCriterion("sCountryNameZh <", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhLessThanOrEqualTo(String value) {
            addCriterion("sCountryNameZh <=", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhLike(String value) {
            addCriterion("sCountryNameZh like", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhNotLike(String value) {
            addCriterion("sCountryNameZh not like", value, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhIn(List<String> values) {
            addCriterion("sCountryNameZh in", values, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhNotIn(List<String> values) {
            addCriterion("sCountryNameZh not in", values, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhBetween(String value1, String value2) {
            addCriterion("sCountryNameZh between", value1, value2, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andCountryNameZhNotBetween(String value1, String value2) {
            addCriterion("sCountryNameZh not between", value1, value2, "countryNameZh");
            return (Criteria) this;
        }

        public Criteria andContinentIsNull() {
            addCriterion("sContinent is null");
            return (Criteria) this;
        }

        public Criteria andContinentIsNotNull() {
            addCriterion("sContinent is not null");
            return (Criteria) this;
        }

        public Criteria andContinentEqualTo(String value) {
            addCriterion("sContinent =", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotEqualTo(String value) {
            addCriterion("sContinent <>", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentGreaterThan(String value) {
            addCriterion("sContinent >", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentGreaterThanOrEqualTo(String value) {
            addCriterion("sContinent >=", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLessThan(String value) {
            addCriterion("sContinent <", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLessThanOrEqualTo(String value) {
            addCriterion("sContinent <=", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLike(String value) {
            addCriterion("sContinent like", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotLike(String value) {
            addCriterion("sContinent not like", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentIn(List<String> values) {
            addCriterion("sContinent in", values, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotIn(List<String> values) {
            addCriterion("sContinent not in", values, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentBetween(String value1, String value2) {
            addCriterion("sContinent between", value1, value2, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotBetween(String value1, String value2) {
            addCriterion("sContinent not between", value1, value2, "continent");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("sFlag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("sFlag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("sFlag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("sFlag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("sFlag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("sFlag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("sFlag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("sFlag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("sFlag like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("sFlag not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("sFlag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("sFlag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("sFlag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("sFlag not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeIsNull() {
            addCriterion("dProhibitedStartTime is null");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeIsNotNull() {
            addCriterion("dProhibitedStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeEqualTo(String value) {
            addCriterion("dProhibitedStartTime =", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeNotEqualTo(String value) {
            addCriterion("dProhibitedStartTime <>", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeGreaterThan(String value) {
            addCriterion("dProhibitedStartTime >", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("dProhibitedStartTime >=", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLessThan(String value) {
            addCriterion("dProhibitedStartTime <", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLessThanOrEqualTo(String value) {
            addCriterion("dProhibitedStartTime <=", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLike(String value) {
            addCriterion("dProhibitedStartTime like", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeNotLike(String value) {
            addCriterion("dProhibitedStartTime not like", value, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeIn(List<String> values) {
            addCriterion("dProhibitedStartTime in", values, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeNotIn(List<String> values) {
            addCriterion("dProhibitedStartTime not in", values, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeBetween(String value1, String value2) {
            addCriterion("dProhibitedStartTime between", value1, value2, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeNotBetween(String value1, String value2) {
            addCriterion("dProhibitedStartTime not between", value1, value2, "prohibitedStartTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeIsNull() {
            addCriterion("dProhibitedEndTime is null");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeIsNotNull() {
            addCriterion("dProhibitedEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeEqualTo(String value) {
            addCriterion("dProhibitedEndTime =", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeNotEqualTo(String value) {
            addCriterion("dProhibitedEndTime <>", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeGreaterThan(String value) {
            addCriterion("dProhibitedEndTime >", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("dProhibitedEndTime >=", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLessThan(String value) {
            addCriterion("dProhibitedEndTime <", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLessThanOrEqualTo(String value) {
            addCriterion("dProhibitedEndTime <=", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLike(String value) {
            addCriterion("dProhibitedEndTime like", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeNotLike(String value) {
            addCriterion("dProhibitedEndTime not like", value, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeIn(List<String> values) {
            addCriterion("dProhibitedEndTime in", values, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeNotIn(List<String> values) {
            addCriterion("dProhibitedEndTime not in", values, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeBetween(String value1, String value2) {
            addCriterion("dProhibitedEndTime between", value1, value2, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeNotBetween(String value1, String value2) {
            addCriterion("dProhibitedEndTime not between", value1, value2, "prohibitedEndTime");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalIsNull() {
            addCriterion("dProhibitedStartTimeLocal is null");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalIsNotNull() {
            addCriterion("dProhibitedStartTimeLocal is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalEqualTo(String value) {
            addCriterion("dProhibitedStartTimeLocal =", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalNotEqualTo(String value) {
            addCriterion("dProhibitedStartTimeLocal <>", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalGreaterThan(String value) {
            addCriterion("dProhibitedStartTimeLocal >", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalGreaterThanOrEqualTo(String value) {
            addCriterion("dProhibitedStartTimeLocal >=", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalLessThan(String value) {
            addCriterion("dProhibitedStartTimeLocal <", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalLessThanOrEqualTo(String value) {
            addCriterion("dProhibitedStartTimeLocal <=", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalLike(String value) {
            addCriterion("dProhibitedStartTimeLocal like", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalNotLike(String value) {
            addCriterion("dProhibitedStartTimeLocal not like", value, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalIn(List<String> values) {
            addCriterion("dProhibitedStartTimeLocal in", values, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalNotIn(List<String> values) {
            addCriterion("dProhibitedStartTimeLocal not in", values, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalBetween(String value1, String value2) {
            addCriterion("dProhibitedStartTimeLocal between", value1, value2, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedStartTimeLocalNotBetween(String value1, String value2) {
            addCriterion("dProhibitedStartTimeLocal not between", value1, value2, "prohibitedStartTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalIsNull() {
            addCriterion("dProhibitedEndTimeLocal is null");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalIsNotNull() {
            addCriterion("dProhibitedEndTimeLocal is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalEqualTo(String value) {
            addCriterion("dProhibitedEndTimeLocal =", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalNotEqualTo(String value) {
            addCriterion("dProhibitedEndTimeLocal <>", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalGreaterThan(String value) {
            addCriterion("dProhibitedEndTimeLocal >", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalGreaterThanOrEqualTo(String value) {
            addCriterion("dProhibitedEndTimeLocal >=", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalLessThan(String value) {
            addCriterion("dProhibitedEndTimeLocal <", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalLessThanOrEqualTo(String value) {
            addCriterion("dProhibitedEndTimeLocal <=", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalLike(String value) {
            addCriterion("dProhibitedEndTimeLocal like", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalNotLike(String value) {
            addCriterion("dProhibitedEndTimeLocal not like", value, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalIn(List<String> values) {
            addCriterion("dProhibitedEndTimeLocal in", values, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalNotIn(List<String> values) {
            addCriterion("dProhibitedEndTimeLocal not in", values, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalBetween(String value1, String value2) {
            addCriterion("dProhibitedEndTimeLocal between", value1, value2, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andProhibitedEndTimeLocalNotBetween(String value1, String value2) {
            addCriterion("dProhibitedEndTimeLocal not between", value1, value2, "prohibitedEndTimeLocal");
            return (Criteria) this;
        }

        public Criteria andTimeZoneIsNull() {
            addCriterion("sTimeZone is null");
            return (Criteria) this;
        }

        public Criteria andTimeZoneIsNotNull() {
            addCriterion("sTimeZone is not null");
            return (Criteria) this;
        }

        public Criteria andTimeZoneEqualTo(String value) {
            addCriterion("sTimeZone =", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneNotEqualTo(String value) {
            addCriterion("sTimeZone <>", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneGreaterThan(String value) {
            addCriterion("sTimeZone >", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneGreaterThanOrEqualTo(String value) {
            addCriterion("sTimeZone >=", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneLessThan(String value) {
            addCriterion("sTimeZone <", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneLessThanOrEqualTo(String value) {
            addCriterion("sTimeZone <=", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneLike(String value) {
            addCriterion("sTimeZone like", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneNotLike(String value) {
            addCriterion("sTimeZone not like", value, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneIn(List<String> values) {
            addCriterion("sTimeZone in", values, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneNotIn(List<String> values) {
            addCriterion("sTimeZone not in", values, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneBetween(String value1, String value2) {
            addCriterion("sTimeZone between", value1, value2, "timeZone");
            return (Criteria) this;
        }

        public Criteria andTimeZoneNotBetween(String value1, String value2) {
            addCriterion("sTimeZone not between", value1, value2, "timeZone");
            return (Criteria) this;
        }

        public Criteria andActionIsNull() {
            addCriterion("iAction is null");
            return (Criteria) this;
        }

        public Criteria andActionIsNotNull() {
            addCriterion("iAction is not null");
            return (Criteria) this;
        }

        public Criteria andActionEqualTo(Integer value) {
            addCriterion("iAction =", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotEqualTo(Integer value) {
            addCriterion("iAction <>", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThan(Integer value) {
            addCriterion("iAction >", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThanOrEqualTo(Integer value) {
            addCriterion("iAction >=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThan(Integer value) {
            addCriterion("iAction <", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThanOrEqualTo(Integer value) {
            addCriterion("iAction <=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionIn(List<Integer> values) {
            addCriterion("iAction in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotIn(List<Integer> values) {
            addCriterion("iAction not in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionBetween(Integer value1, Integer value2) {
            addCriterion("iAction between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotBetween(Integer value1, Integer value2) {
            addCriterion("iAction not between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("iGroupId is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("iGroupId is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("iGroupId =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("iGroupId <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("iGroupId >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("iGroupId >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("iGroupId <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("iGroupId <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("iGroupId in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("iGroupId not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("iGroupId between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("iGroupId not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdIsNull() {
            addCriterion("iCountryGroupId is null");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdIsNotNull() {
            addCriterion("iCountryGroupId is not null");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdEqualTo(Integer value) {
            addCriterion("iCountryGroupId =", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdNotEqualTo(Integer value) {
            addCriterion("iCountryGroupId <>", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdGreaterThan(Integer value) {
            addCriterion("iCountryGroupId >", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("iCountryGroupId >=", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdLessThan(Integer value) {
            addCriterion("iCountryGroupId <", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("iCountryGroupId <=", value, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdIn(List<Integer> values) {
            addCriterion("iCountryGroupId in", values, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdNotIn(List<Integer> values) {
            addCriterion("iCountryGroupId not in", values, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("iCountryGroupId between", value1, value2, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andCountryGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("iCountryGroupId not between", value1, value2, "countryGroupId");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("iSort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("iSort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("iSort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("iSort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("iSort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("iSort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("iSort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("iSort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("iSort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("iSort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("iSort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("iSort not between", value1, value2, "sort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table App_Country
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 17 15:29:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}