package com.ymatou.liveinfo.infrastructure.db.mapper;

import com.ymatou.liveinfo.infrastructure.db.model.ActivityExample;
import com.ymatou.liveinfo.infrastructure.db.model.ActivityPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int insert(ActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int insertSelective(ActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    List<ActivityPo> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    ActivityPo selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityPo record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByExample(@Param("record") ActivityPo record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_Activity
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByPrimaryKey(ActivityPo record);
}