package com.ymatou.liveinfo.infrastructure.db.mapper;

import com.ymatou.liveinfo.infrastructure.db.model.CountryExample;
import com.ymatou.liveinfo.infrastructure.db.model.CountryPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int countByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int deleteByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int deleteByPrimaryKey(Integer countryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int insert(CountryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int insertSelective(CountryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    List<CountryPo> selectByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    CountryPo selectByPrimaryKey(Integer countryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountryPo record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByExample(@Param("record") CountryPo record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByPrimaryKeySelective(CountryPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table App_Country
     *
     * @mbggenerated Mon Apr 17 15:29:22 CST 2017
     */
    int updateByPrimaryKey(CountryPo record);
}